### ISSUE TITLE
Updater: JavaScript error

### ISSUE THREAD

**Issue by nepomuc** [phpList/updater#87]
When calling the updater via https://example.com/lists/updater/ a JavaScript error pops up in the console. There seems to be a mistake with counting the steps, or the server response "-1" is not correct. Looking at the current JavaScript code it would have to be 0 to work. But not it returns -1. Rhe first line in executeNextStep() adds 1 to it which results in 0, but since stepActionMap in setCurrentActionItem() counts by beginning at 1 the entire updater doesn't work.

![image](https://user-images.githubusercontent.com/864660/97549535-cc839700-19d0-11eb-84b9-fa952ef36bc9.png)

**Comment by michield** [comment]
I can't replicate the error you get. I get this one, but it seems harmless and the update works fine.

![image](https://user-images.githubusercontent.com/569843/100345449-401dc180-2fda-11eb-8e30-e5a310f06c4d.png)

**Comment by michield** [comment]
If you can find the issue on your system, it will be great to submit a PR for it.

**Comment by nepomuc** [comment]
Too bad. I would like to try to reinstall phpList manually, but without losing my data and config. Is there an instruction how to do that? https://www.phplist.org/manual/books/phplist-manual/page/installing-phplist-manually doesn't seem to cover this.

**Comment by michield** [comment]
Yes, you can just overwrite the code with the latest and keep your config file. That will preserve the data and config.

**Comment by michield** [comment]
Here are the upgrade instructions: https://www.phplist.org/download-phplist/
